[build]
  base = "."
  publish = "dist"
  command = "bun run build"

[dev]
  command = "bun run dev"
  port = 5173
  publish = "dist"
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[images]
  remote_images = [
    "https://images.unsplash.com/**"
  ]
